version: "3"
services:
  main_nginx:
    container_name: epds-aphrodite_main-nginx
    build:
      context: ./main-nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 7070:80
    depends_on:
      - main-app
      - pdfjs
      - main-api
  main-app:
    container_name: epds-aphrodite_main-app
    build:
      context: ./main-app
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - /usr/src/app/node_modules
      - ./main-app:/usr/src/app
  pdfjs:
    container_name: epds-aphrodite_pdfjs
    build:
      context: ./pdfjs
      dockerfile: Dockerfile
  main-api:
    container_name: epds-aphrodite_main-api
    build:
      context: ./main-api
      dockerfile: Dockerfile
    volumes:
      - /usr/src/app/node_modules
      - ./main-api:/usr/src/app
      - ./files:/usr/src/files
    environment:
      - REDIS_HOST=queue-redis
      - FILE_PATH=/usr/src/files
  queue-redis:
    container_name: epds-aphrodite_queue-redis
    image: redis:6-alpine
