version: "3"
services:
  main_nginx:
    container_name: epds-aphrodite_main-nginx
    build:
      context: ./main-nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 7070:80
    depends_on:
      - main-app
      - pdfjs
      - main-api
  main-app:
    container_name: epds-aphrodite_main-app
    build:
      context: ./main-app
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - /usr/src/app/node_modules
      - ./main-app:/usr/src/app
  pdfjs:
    container_name: epds-aphrodite_pdfjs
    build:
      context: ./pdfjs
      dockerfile: Dockerfile
  main-api:
    container_name: epds-aphrodite_main-api
    build:
      context: ./main-api
      dockerfile: Dockerfile
    environment:
      - DOMAIN=http://localhost:7070
      - DB_HOST=host.docker.internal
      - DB_PASSWORD=Mbisla@18
      - DB_NAME=aphrodite
      - REDIS_HOST=queue-redis
      - FILE_PATH=/usr/src/files
      - BARCODE_LICENSE=t0068NQAAAEsnp86A2NZdml4Heh3CIwJq3m/tenO5/NDZl6zGcnHzTRrV722gnmfPwjY2xwxagR/xQJZIMxRb3DwxnbpFAJg=
      - AZURE_AD_CLIENT_ID=13bd7dbf-1e35-4dc2-b5f7-e8c26d6f8a3d
      - AZURE_AD_TENANT_ID=f5fd42b7-4db5-4b3e-aaa6-f2e5542f7357
      - MAIL_HOST=a
      - MAIL_PORT=1
      - MAIL_USER=a
      - MAIL_PASSWORD=a
      - MAIL_FROM=a
    volumes:
      - /usr/src/app/node_modules
      - ./main-api:/usr/src/app
      - ./files:/usr/src/files
  queue-redis:
    container_name: epds-aphrodite_queue-redis
    image: redis:6-alpine
  # main-db:
  #   container_name: epds-aphrodite_main-db
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   ports:
  #     - 1433:1433
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=Mbisla@18
  #   volumes:
  #     - epds-aphrodite_main-db_volume:/var/opt/mssql

# volumes:
#   epds-aphrodite_main-db_volume:
#     external: true
