export interface UploadDocToSpringParams {
  Brand: string;
  CompanyCode: string;
  ContractNo: string;
  ProjectCode: string;
  Tower_Phase: string;
  CustomerCode: string;
  ProjectName: string;
  CustomerName: string;
  UnitDescription: string;
  DocumentGroupID: string;
  DocumentGroupDescription: string;
  DocumentGroupShortDescription: string;
  DocumentTypeID: string;
  DocumentTypeDescription: string;
  DocumentTypeShortDescription: string;
  DocumentName: string;
  ExternalSourceCaptureDate: string;
  FileName: string;
  MIMEType: string;
  DocumentDate: string;
  ExternalSourceUserID: string;
  SourceSystem: string;
  DataCapDocSource: string;
  DataCapRemarks: string;
  Remarks: string;
  FileSize: string;
  B64Attachment: string;
}
