export enum ActivityLogType {
  ADD_USER = 'ADD_USER',
  EDIT_USER = 'EDIT_USER',
  ADD_NOMENCLATURE_LOOKUP = 'ADD_NOMENCLATURE_LOOKUP',
  EDIT_NOMENCLATURE_LOOKUP = 'EDIT_NOMENCLATURE_LOOKUP',
  DELETE_NOMENCLATURE_LOOKUP = 'DELETE_NOMENCLATURE_LOOKUP',
  ADD_NOMENCLATURE_WHITELIST = 'ADD_NOMENCLATURE_WHITELIST',
  EDIT_NOMENCLATURE_WHITELIST = 'EDIT_NOMENCLATURE_WHITELIST',
  DELETE_NOMENCLATURE_WHITELIST = 'DELETE_NOMENCLATURE_WHITELIST',
}
