export enum DocumentStatus {
  UPLOADED = 'UPLOADED',
  QR_BEGIN = 'QR_BEGIN',
  QR_DONE = 'QR_DONE',
  QR_FAILED = 'QR_FAILED',
  INDEXING_BEGIN = 'INDEXING_BEGIN',
  INDEXING_DONE = 'INDEXING_DONE',
  INDEXING_FAILED = 'INDEXING_FAILED',
  MIGRATE_BEGIN = 'MIGRATE_BEGIN',
  MIGRATE_DONE = 'MIGRATE_DONE',
  MIGRATE_FAILED = 'MIGRATE_FAILED',
}
