BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.[document]
	DROP CONSTRAINT FK_document_user
GO
ALTER TABLE dbo.[user] SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
EXECUTE sp_rename N'dbo.[document].springReqParams', N'Tmp_springcmReqParams', 'COLUMN' 
GO
EXECUTE sp_rename N'dbo.[document].Tmp_springcmReqParams', N'springcmReqParams', 'COLUMN' 
GO
ALTER TABLE dbo.[document] ADD CONSTRAINT
	FK_document_user FOREIGN KEY
	(
	userUsername
	) REFERENCES dbo.[user]
	(
	username
	) ON UPDATE  CASCADE 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.[document] SET (LOCK_ESCALATION = TABLE)
GO
COMMIT