BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
EXECUTE sp_rename N'dbo.[user].IsActive', N'Tmp_isActive', 'COLUMN' 
GO
EXECUTE sp_rename N'dbo.[user].Tmp_isActive', N'isActive', 'COLUMN' 
GO
ALTER TABLE dbo.[user]
	DROP CONSTRAINT DF_user_isDeleted
GO
ALTER TABLE dbo.[user]
	DROP COLUMN isDeleted
GO
ALTER TABLE dbo.[user] 
	ALTER COLUMN firstName nvarchar(255) NOT NULL
ALTER TABLE dbo.[user] 
	ALTER COLUMN lastName nvarchar(255) NOT NULL
GO
ALTER TABLE dbo.[user] ADD
	objectId nvarchar(MAX) NOT NULL
	DEFAULT 'N/A'
GO
ALTER TABLE dbo.[user] SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
