BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.[document] ADD
	documentDate datetime NULL,
	encoder int NULL,
	encodedAt datetime NULL,
	checker int NULL,
	checkedAt datetime NULL,
	approver int NULL
GO
ALTER TABLE dbo.[document] SET (LOCK_ESCALATION = TABLE)
GO
COMMIT