BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.nomenclature
	(
	id int NOT NULL IDENTITY (1, 1),
	description nvarchar(255) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.nomenclature SET (LOCK_ESCALATION = TABLE)
GO
COMMIT