UPDATE dh 
SET dh.userUsername = u.username
FROM dbo.document_history as dh
INNER JOIN dbo.[user] as u
ON u.id = dh.userUsername

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.[user] SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.document_history ADD CONSTRAINT
	FK_document_history_user FOREIGN KEY
	(
	userUsername
	) REFERENCES dbo.[user]
	(
	username
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.document_history SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
