BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.[document] 
	ALTER COLUMN userId nvarchar(255) NOT NULL
ALTER TABLE dbo.[document] 
	ALTER COLUMN modifiedBy nvarchar(255) NULL
ALTER TABLE dbo.[document] 
	ALTER COLUMN encoder nvarchar(255) NULL
ALTER TABLE dbo.[document] 
	ALTER COLUMN checker nvarchar(255) NULL
ALTER TABLE dbo.[document] 
	ALTER COLUMN approver nvarchar(255) NULL
GO
ALTER TABLE dbo.[document] SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

