BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
EXECUTE sp_rename N'dbo.document_history.userId', N'Tmp_userUsername', 'COLUMN' 
GO
EXECUTE sp_rename N'dbo.document_history.Tmp_userUsername', N'userUsername', 'COLUMN' 
GO
ALTER TABLE dbo.document_history SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
