BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.[document]
	DROP CONSTRAINT FK_7424ddcbdf1e9b067669eb0d3fd
GO
ALTER TABLE dbo.document_history
	DROP CONSTRAINT FK_3c5d2cf18513d9baa390fdf3260
GO
EXECUTE sp_rename N'dbo.[user].email', N'Tmp_username_5', 'COLUMN' 
GO
EXECUTE sp_rename N'dbo.[user].Tmp_username_5', N'username', 'COLUMN' 
GO
ALTER TABLE dbo.[user]
	DROP CONSTRAINT PK_cace4a159ff9f2512dd42373760
GO
ALTER TABLE dbo.[user] ADD CONSTRAINT
	PK_cace4a159ff9f2512dd42373760 PRIMARY KEY CLUSTERED 
	(
	username
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.[user] SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.document_history SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.[document] SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
